name: CI/CD Pipeline
on: 
 push:
  branches:
   - main
jobs:
 deploy: 
  runs-on: ubuntu-latest
  steps:
  - name: Checkout Code
    uses: actions/checkout@v3
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  - name: Build Image
    run: docker build -t ${{ secrets.DOCKER_USERNAME}}/project-app .
  - name: Push Image
    run: docker push ${{secrets.DOCKER_USERNAME }}/project-app 
  - name: Deploy to EC2
    uses: appleboy/ssh-action@v0.1.6  
    with: 
      host: ${{secrets.EC2_HOST }}
      username: ${{secrets.EC2_USER }} 
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/project-app
        docker stop app || true
        docker rm app || true
	docker ps -q --filter "publish=5000" | xargs -r docker stop
	docker ps -aq --filter "publish=5000" | xargs -r docker rm
	docker run -d -p 5000:5000 --name app --restart=always \ 
	${{ secrets.DOCKER_USERNAME }}/project-app
